### PR TITLE
Instead of using fixed key and secret try to derive authorization from IAM roles

### PR DESCRIPTION
**Pull request by hseffler**
Instead of using fixed key and secret try to derive authorization from IAM roles, which is a actually a best practice and avoid the need to hardcode sensitive information in every ec2 sdk user.

### CODE REVIEW

**Comment by mhardin** [comment]
Hi @hseffler, were you able to test these proposed changes as working?

**Comment by hseffler** [comment]
Yes, they have been and I also tried to update the documentation. If you have any specific questions to specific changes I would be more than happy to answer them.

**Comment by mhardin** [comment]
Great.  I left one code review comment...if you can address that, we can get this merged over

**Comment by hseffler** [comment]
OK, included your code review remarks.

**Pull request merged**
